ALTER TABLE "User" ADD COLUMN "age" INTEGER;
ALTER TABLE "User" ADD COLUMN "district" TEXT;
ALTER TABLE "User" ADD COLUMN "occupation" TEXT;
ALTER TABLE "User" ADD COLUMN "interests" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "User" ADD COLUMN "goals" TEXT NOT NULL DEFAULT '[]';
